### ISSUE TITLE
Certain columns incorrectly tag 'OAK' games as 'LV' within legacy PBP data

### ISSUE THREAD

**Issue by Metlover** [guga31bb/nflfastR-data#12]
Have not checked if this exists in other datasets but did notice it while parsing legacy PBP data this afternoon.

    > require(dplyr)
    > games = readRDS(url(paste0('https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/legacy-data/play_by_play_2001.rds')))
    > games %>%
    +     filter(posteam == 'LV') %>% 
    +     select(c(play_id, game_id, home_team, away_team, posteam, posteam_type, defteam, side_of_field)) %>% 
    +     head()

    # A tibble: 6 x 8
      play_id    game_id home_team away_team posteam posteam_type defteam side_of_field
        <dbl>      <dbl> <chr>     <chr>     <chr>   <chr>        <chr>   <chr>        
    1      35 2001090907 KC        LV        LV      away         KC      KC           
    2      57 2001090907 KC        LV        LV      away         KC      OAK          
    3      78 2001090907 KC        LV        LV      away         KC      OAK          
    4      96 2001090907 KC        LV        LV      away         KC      OAK          
    5     117 2001090907 KC        LV        LV      away         KC      OAK          
    6     153 2001090907 KC        LV        LV      away         KC      KC 
    
Believe that this is a bug because of inconsistencies with the rest of the dataset (i.e. `side_of_field` still lists `OAK` instead of `LV` ~~and games prior to the 2016 season list `SD` as the team code instead of `LAC`).~~

Edit: Was mistaken on the second part, my apologies -- in which case, perhaps side_of_field should be represented as "LV" then?

**Comment by guga31bb** [comment]
Yep this is something we just fixed in the new version of `nflfastR` in the past week. Since we're not touching legacy-data anymore, it won't get fixed there, but all of this should be standardized in the new data.

**Comment by Metlover** [comment]
Good to know. Appreciate the prompt response!
