### ISSUE TITLE
Question: rosters with new id?

### ISSUE THREAD

**Issue by egor006** [guga31bb/nflfastR-data#14]
Does the roster data not include the new ids? Here is what I'm getting, am I missing something?

Index(['team.season', 'teamPlayers.displayName', 'teamPlayers.firstName',
       'teamPlayers.middleName', 'teamPlayers.lastName', 'teamPlayers.suffix',
       'teamPlayers.status', 'teamPlayers.positionGroup',
       'teamPlayers.position', 'teamPlayers.nflId', 'teamPlayers.esbId',
       'teamPlayers.gsisId', 'teamPlayers.birthDate', 'teamPlayers.homeTown',
       'teamPlayers.collegeId', 'teamPlayers.collegeName',
       'teamPlayers.jerseyNumber', 'teamPlayers.height', 'teamPlayers.weight',
       'team.teamId', 'team.abbr', 'team.cityState', 'team.fullName',
       'team.nick', 'team.conferenceAbbr', 'team.divisionAbbr',
       'teamPlayers.headshot_url', 'teamPlayers.profile_url'],
      dtype='object')

**Comment by guga31bb** [comment]
No, we have not found a way to obtain roster data under the new NFL data system
