### ISSUE TITLE
CSV version of the schedule

### ISSUE THREAD

**Issue by DaSkunk** [guga31bb/nflfastR-data#15]
Would it be possible to generate and store a text version (e.g. CSV, XML, etc) of the 2020 schedule?  Thank you.

**Comment by guga31bb** [comment]
This is the underlying source for the schedule data, which includes 1999 - 2020 and updates https://raw.githubusercontent.com/leesharpe/nfldata/master/data/games.csv

**Comment by DaSkunk** [comment]
Perfect!!  Thank you so much for providing that info.
