### ISSUE TITLE
Add nflfastR version to commit message

### ISSUE THREAD

**Issue by mrcaseb** [guga31bb/nflfastR-data#18]
If we update the data it could help the people out there to know which nflfastR version was used. 
Can be done with 
```r
utils::packageVersion("nflfastR")
```

**Comment by guga31bb** [comment]
Good idea. Added in https://github.com/guga31bb/nflfastR-data/commit/8990ff6d3191bcd5947d0101dc3b2c78c9e85374#diff-85db842e4df4b75fc44bc8a0b5c22955R63
