### ISSUE TITLE
record separator (\n) found in three records 

### ISSUE THREAD

**Issue by MargareeMan** [guga31bb/nflfastR-data#20]
I apologize beforehand if this is an artifact of how I am importing the csv files into my PostgreSQL database (on Windows 10).  But, I found four records in which the "\n" character created a newline between playid and the remainder of the record, for example:

"86097:6: actual: record separator (\n), expected: value
86098:1: ERROR: null value in column "playid" violates not-null constraint   Detail: Failing row contains (null, 2000_16_NYG_DAL," ... and the remainder of the record.

The four records are:

1894, 2000_16_NYG_DAL, 2000121711, drive 14
2943, 2002_15_JAX_CIN, 2002121506, drive 16
1722. 2004_12_CHI_DAL, 2004112501, drive 15
3558, 2006_08_NYJ_CLE, 2006102909, drive 23

Sorry about the issue title.  It should read four records

**Comment by mrcaseb** [comment]
Are you using the R package at all? We have added support for multiple DBI drivers such as `RPostgres::Postgres()` to the database function `update_db()`. 

Something like this should work

```r
your_table <- "name of your table"
your_conn <- DBI::dbConnect(RPostgres::Postgres(),dbname = 'DATABASE_NAME', 
                 host = 'HOST', 
                 port = 5432, # or any other port specified by your DBA
                 user = 'USERNAME',
                 password = 'PASSWORD')

nflfastR::update_db(tblname = your_table, db_connection = your_conn)
```

Please see https://mrcaseb.github.io/nflfastR/reference/update_db.html for further information.

**Comment by MargareeMan** [comment]
I apologize for not picking this up earlier.  This works fine.  Great work!  To answer your question, yes I had built my own database, table, fields and indices and I was loading the data from the csv files.  That I why I had the newline errors and problems with a primary index that required unique play-drive-game ids.  I just now successfully used the above connection to load the recent update to a newly created table without indices.  Thanks greatly for your response and all your work.  I will close this issue.
