### ISSUE TITLE
game clock remains unchanged over several plays then jumps (repeated throughout the game) in 274 games

### ISSUE THREAD

**Issue by MargareeMan** [guga31bb/nflfastR-data#21]
I am certain that this is not an issue with nflfastR code and that the problem was at the recording source.  However, it is a data issue and I think users should be aware of it before doing any elapsed-time analysis of play sequences with the 1999 and 2000 data.  I do apologize beforehand if this type of issue is not considered relevant to this project (in which case I will expect the issue to be closed).  

The maximum number of plays during which the clock remains unchanged ranges from 21 to 7 plays, with the mean = 12 plays

The 274 games in which the clock is repeatedly incorrect over sequences of plays are:

{"1999_01_ARI_PHI", "1999_01_BUF_IND", "1999_01_CAR_NO", \
"1999_01_CIN_TEN", "1999_01_DAL_WAS", "1999_01_DET_SEA", \
"1999_01_KC_CHI", "1999_01_MIA_DEN", "1999_01_MIN_ATL", \
"1999_01_NE_NYJ", "1999_01_NYG_TB", "1999_01_OAK_GB", \
"1999_01_PIT_CLE", "1999_01_SF_JAX", "1999_02_ARI_MIA", \
"1999_02_ATL_DAL", "1999_02_CLE_TEN", "1999_02_DEN_KC", \
"1999_02_GB_DET", "1999_02_IND_NE", "1999_02_JAX_CAR", \
"1999_02_NO_SF", "1999_02_NYJ_BUF", "1999_02_OAK_MIN", \
"1999_02_PIT_BAL", "1999_02_SD_CIN", "1999_02_SEA_CHI", \
"1999_02_TB_PHI", "1999_02_WAS_NYG", "1999_03_ATL_STL", \
"1999_03_CHI_OAK", "1999_03_CIN_CAR", "1999_03_CLE_BAL", \
"1999_03_DEN_TB", "1999_03_DET_KC", "1999_03_IND_SD", \
"1999_03_MIN_GB", "1999_03_NYG_NE", "1999_03_PHI_BUF", \
"1999_03_SEA_PIT", "1999_03_SF_ARI", "1999_03_TEN_JAX", \
"1999_03_WAS_NYJ", "1999_04_ARI_DAL", "1999_04_BAL_ATL", \
"1999_04_BUF_MIA", "1999_04_CAR_WAS", "1999_04_JAX_PIT", \
"1999_04_KC_SD", "1999_04_NE_CLE", "1999_04_NO_CHI", \
"1999_04_NYJ_DEN", "1999_04_OAK_SEA", "1999_04_PHI_NYG", \
"1999_04_STL_CIN", "1999_04_TB_MIN", "1999_04_TEN_SF", \
"1999_05_ATL_NO", "1999_05_BAL_TEN", "1999_05_CHI_MIN", \
"1999_05_CIN_CLE", "1999_05_DAL_PHI", "1999_05_DEN_OAK", \
"1999_05_JAX_NYJ", "1999_05_MIA_IND", "1999_05_NE_KC", \
"1999_05_NYG_ARI", "1999_05_PIT_BUF", "1999_05_SD_DET", \
"1999_05_SF_STL", "1999_05_TB_GB", "1999_06_CAR_SF", \
"1999_06_CLE_JAX", "1999_06_DAL_NYG", "1999_06_GB_DEN", \
"1999_06_IND_NYJ", "1999_06_MIA_NE", "1999_06_MIN_DET", \
"1999_06_OAK_BUF", "1999_06_PHI_CHI", "1999_06_PIT_CIN", \
"1999_06_SEA_SD", "1999_06_STL_ATL", "1999_06_TEN_NO", \
"1999_06_WAS_ARI", "1999_07_ATL_PIT", "1999_07_BUF_SEA", \
"1999_07_CHI_TB", "1999_07_CIN_IND", "1999_07_CLE_STL", \
"1999_07_DEN_NE", "1999_07_DET_CAR", "1999_07_GB_SD", \
"1999_07_KC_BAL", "1999_07_NO_NYG", "1999_07_NYJ_OAK", \
"1999_07_PHI_MIA", "1999_07_SF_MIN", "1999_07_WAS_DAL", \
"1999_08_BUF_BAL", "1999_08_CAR_ATL", "1999_08_CHI_WAS", \
"1999_08_CLE_NO", "1999_08_DAL_IND", "1999_08_JAX_CIN", \
"1999_08_MIA_OAK", "1999_08_MIN_DEN", "1999_08_NE_ARI", \
"1999_08_NYG_PHI", "1999_08_SD_KC", "1999_08_SEA_GB", \
"1999_08_STL_TEN", "1999_08_TB_DET", "1999_09_ARI_NYJ", \
"1999_09_BAL_CLE", "1999_09_BUF_WAS", "1999_09_CHI_GB", \
"1999_09_CIN_SEA", "1999_09_DAL_MIN", "1999_09_DEN_SD", \
"1999_09_JAX_ATL", "1999_09_KC_IND", "1999_09_PHI_CAR", \
"1999_09_PIT_SF", "1999_09_STL_DET", "1999_09_TB_NO", \
"1999_09_TEN_MIA", "1999_10_BAL_JAX", "1999_10_CAR_STL", \
"1999_10_CLE_PIT", "1999_10_DEN_SEA", "1999_10_DET_ARI", \
"1999_10_GB_DAL", "1999_10_IND_NYG", "1999_10_KC_TB", \
"1999_10_MIA_BUF", "1999_10_MIN_CHI", "1999_10_NYJ_NE", \
"1999_10_SD_OAK", "1999_10_SF_NO", "1999_10_TEN_CIN", \
"1999_10_WAS_PHI", "1999_11_ATL_TB", "1999_11_BAL_CIN", \
"1999_11_BUF_NYJ", "1999_11_CAR_CLE", "1999_11_CHI_SD", \
"1999_11_DAL_ARI", "1999_11_DET_GB", "1999_11_IND_PHI", \
"1999_11_NE_MIA", "1999_11_NO_JAX", "1999_11_NYG_WAS", \
"1999_11_OAK_DEN", "1999_11_PIT_TEN", "1999_11_SEA_KC", \
"1999_11_STL_SF", "1999_12_ARI_NYG", "1999_12_ATL_CAR", \
"1999_12_CHI_DET", "1999_12_CIN_PIT", "1999_12_GB_SF", \
"1999_12_JAX_BAL", "1999_12_KC_OAK", "1999_12_MIA_DAL", \
"1999_12_NE_BUF", "1999_12_NO_STL", "1999_12_NYJ_IND", \
"1999_12_PHI_WAS", "1999_12_SD_MIN", "1999_12_TB_SEA", \
"1999_12_TEN_CLE", "1999_13_CLE_SD", "1999_13_DAL_NE", \
"1999_13_GB_CHI", "1999_13_IND_MIA", "1999_13_KC_DEN", \
"1999_13_MIN_TB", "1999_13_NO_ATL", "1999_13_NYJ_NYG", \
"1999_13_PHI_ARI", "1999_13_PIT_JAX", "1999_13_SEA_OAK", \
"1999_13_SF_CIN", "1999_13_STL_CAR", "1999_13_TEN_BAL", \
"1999_13_WAS_DET", "1999_14_ARI_WAS", "1999_14_ATL_SF", \
"1999_14_BAL_PIT", "1999_14_CAR_GB", "1999_14_CLE_CIN", \
"1999_14_DEN_JAX", "1999_14_DET_TB", "1999_14_MIA_NYJ", \
"1999_14_MIN_KC", "1999_14_NE_IND", "1999_14_NYG_BUF", \
"1999_14_OAK_TEN", "1999_14_PHI_DAL", "1999_14_SD_SEA", \
"1999_14_STL_NO", "1999_15_ATL_TEN", "1999_15_BUF_ARI", \
"1999_15_DET_CHI", "1999_15_GB_MIN", "1999_15_JAX_CLE", \
"1999_15_NE_PHI", "1999_15_NO_BAL", "1999_15_NYG_STL", \
"1999_15_NYJ_DAL", "1999_15_PIT_KC", "1999_15_SD_MIA", \
"1999_15_SEA_DEN", "1999_15_SF_CAR", "1999_15_TB_OAK", \
"1999_15_WAS_IND", "1999_16_ARI_ATL", "1999_16_BUF_NE", \
"1999_16_CAR_PIT", "1999_16_CHI_STL", "1999_16_CIN_BAL", \
"1999_16_DAL_NO", "1999_16_DEN_DET", "1999_16_GB_TB", \
"1999_16_IND_CLE", "1999_16_JAX_TEN", "1999_16_KC_SEA", \
"1999_16_MIN_NYG", "1999_16_NYJ_MIA", "1999_16_OAK_SD", \
"1999_16_WAS_SF", "1999_17_ARI_GB", "1999_17_BAL_NE", \
"1999_17_CIN_JAX", "1999_17_DET_MIN", "1999_17_IND_BUF", \
"1999_17_MIA_WAS", "1999_17_NO_CAR", "1999_17_NYG_DAL", \
"1999_17_OAK_KC", "1999_17_SD_DEN", "1999_17_SEA_NYJ", \
"1999_17_SF_ATL", "1999_17_STL_PHI", "1999_17_TB_CHI", \
"1999_17_TEN_PIT", "2000_01_BAL_PIT", "2000_01_CAR_WAS", \
"2000_01_SD_OAK", "2000_01_SF_ATL", "2000_02_KC_TEN", \
"2000_02_STL_SEA", "2000_02_WAS_DET", "2000_03_ATL_CAR", \
"2000_03_DAL_WAS", "2000_03_DEN_OAK", "2000_03_NO_SEA", \
"2000_03_NYG_CHI", "2000_03_PIT_CLE", "2000_03_TB_DET", \
"2000_04_CLE_OAK", "2000_04_DET_CHI", "2000_04_STL_ATL", \
"2000_04_TEN_PIT", "2000_05_DAL_CAR", "2000_05_MIN_DET", \
"2000_05_NYG_TEN", "2000_05_TB_WAS", "2000_06_GB_DET", \
"2000_06_NO_CHI", "2000_07_JAX_TEN", "2000_10_PIT_TEN", \
"2000_11_BAL_TEN"}

**Comment by guga31bb** [comment]
Yep see

https://github.com/mrcaseb/nflfastR/issues/35#issuecomment-656954185

and

https://github.com/CroppedClamp/nfl_pbps/issues/1
