### ISSUE TITLE
Is the lack of 2020 in raw intentional?

### ISSUE THREAD

**Issue by vita10gy** [guga31bb/nflfastR-data#23]
There is still no 2020 folder with thursdays game in it in 

https://github.com/guga31bb/nflfastR-data/tree/master/raw

Is that intentional and we can't bank on that, or just a new-process hiccup?

**Comment by guga31bb** [comment]
They will be saved here now:

https://github.com/guga31bb/nflfastR-raw/tree/master/raw/2020

**Comment by vita10gy** [comment]
Great! Thanks!
