### ISSUE TITLE
Roster Data

### ISSUE THREAD

**Issue by vita10gy** [guga31bb/nflfastR-data#24]
Is the plan that the roster CSV's get updated at some point? 

Seems to be updating over in nflfastr-raw, but only as .rds.

**Comment by james-childress** [comment]
I checked the rds roster file and it looks like that's not up to date for 2020 either. I don't think anyone has figured out how to get the new rosters yet.

**Comment by vita10gy** [comment]
You checked the roster file in this repository or the one over in 

https://github.com/guga31bb/nflfastR-raw/blob/master/roster/roster.rds

?

**Comment by mrcaseb** [comment]
Roster data is still a work in progress. The mentioned in the nflfastR-raw repo includes 2020 data but it's a development version and we are not 100% sure it's free of bugs.

I'll try to make this stable and we'll announce it officially but for now please use it with caution

**Comment by mrcaseb** [comment]
Roster data are now available in a new repo. 

Please see [my comment in another issue](https://github.com/guga31bb/nflfastR-raw/issues/1#issuecomment-693328200)
