### ISSUE TITLE
How to get every player id + position?

### ISSUE THREAD

**Issue by james-childress** [guga31bb/nflfastR-data#26]
Looking at the roster CSV, I can't find any player id that looks like the ones in the play by play data. For example, Raheem Mostert's rusher id in the play by play data is 32013030-2d30-3033-3136-3837aa36ac48, but his latest entry in the roster csv looks like this:

2019,Raheem Mostert,Raheem,Raheem,Mostert,NA,ACT,RB,RB,2553728,MOS822492,00-0031687,04/09/1992,"Daytona Beach, FL",1631,Purdue,31,5-10,205,4500,SF,San Francisco,San Francisco 49ers,49ers,NFC,NCW,http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/MOS822492.png,http://www.nfl.com/player/raheemmostert/2553728/profile

Is there a different id in the play by play data that maps to what's available in the roster csv? Or is there another data source that maps the player ids in the play by play data to their positions?

**Comment by vita10gy** [comment]
00-0031687 is the old id

 32013030-2d30-3033-3136-3837aa36ac48 is the new one

You can use https://github.com/guga31bb/nflfastR-data/blob/master/roster-data/legacy_id_map.csv to marry those up for some players, but as of yet there's no magic bullet. 

It might be the case we just have to collectively brute force it. If I could get an updated roster at all I have a process of manually matching up players as needed, so I could expand on that mapping file.

**Comment by mrcaseb** [comment]
The NFL changed it's play by play source this offseason and now we only have those GUIDs like 32013030-2d30-3033-3136-3837aa36ac48. We tried to find a source for the complete roster data with those IDs but didn't find anything yet. 

I am currently working on a join of play by play IDs to scraped rosters buit it's not done yet. We'll announce officially if we have a stable solution

**Comment by mrcaseb** [comment]
Roster data are now available in a new repo. 

Please see [my comment in another issue](https://github.com/guga31bb/nflfastR-raw/issues/1#issuecomment-693328200)
