### ISSUE TITLE
play_by_play_2020.csv  Drive count error

### ISSUE THREAD

**Issue by asantana810** [guga31bb/nflfastR-data#29]
The drive column ( column 19 of CSV) is not accurate.  The count does not update accurately after punts and turnovers; possessing team changes but drive count lags.

![image](https://user-images.githubusercontent.com/71782537/94044467-2e325f00-fd9c-11ea-827c-e7e5ffac514e.png)

**Comment by guga31bb** [comment]
The `drive` column is provided by the NFL and is very buggy. See https://github.com/mrcaseb/nflfastR/issues/36. We offer `fixed_drive` which is an improvement and I would suggest using that instead
