### ISSUE TITLE
Player ID format seems to be incorrect in play by play data repository

### ISSUE THREAD

**Issue by tgaydos** [guga31bb/nflfastR-data#30]
The passer_id, rusher_id, and receiver_id items in the play by play data have values such as:
32013030-2d30-3032-3334-35395dc60da5

In the legacy-data, these items have values such as:
00-0023459

The player id's in the current data repository do not match anything in the roster data repository, while the legacy-data values match the gsis_id in the rosters.

**Comment by mrcaseb** [comment]
That's not incorrect. The new NFL api uses those long player IDs instead of the old gsis ids.

However, the newest development version of nflfastR offers the function `decode_player_ids()` to decode the new ids into the old GSIS IDs.  

For current roster data please use `fast_scraper_roster()`

**Comment by tgaydos** [comment]
Thanks, I thought I might be missing something - decode_player_ids() just what I needed. 

Now everything is working for me, except that for some reason Ryan Izzo and Tyler Conklin have their gsis_ids swapped after i run decode_player_ids(). All other players are decoded correctly.


    On Thursday, September 24, 2020, 8:40:17 AM EDT, mrcaseb <notifications@github.com> wrote:  
 
 


That's not incorrect. The new NFL api uses those long player IDs instead of the old gsis ids.

However, the newest development version of nflfastR offers the function decode_player_ids() to decode the new ids into the old GSIS IDs.

For current roster data please use fast_scraper_roster()

**Comment by mrcaseb** [comment]
Yeah it looks like the swapped IDs are an issue in the underlying data. 
https://github.com/mrcaseb/nflfastR-roster/issues/3
