### ISSUE TITLE
Pass Touchdown Reversed -- CHI-WASH Game

### ISSUE THREAD

**Issue by mfiorina** [guga31bb/nflfastR-data#31]
Hello,

Tiny tiny thing-- In the PBP data, game_id: "2020_03_CHI_ATL", play_id: 3651, which has the following description:

"(10:49) (Shotgun) 9-N.Foles pass deep middle to 17-A.Miller for 17 yards, TOUCHDOWN.\r\nThe Replay Official reviewed the pass completion ruling, and the play was REVERSED.\r\n(Shotgun) 9-N.Foles pass incomplete deep middle to 17-A.Miller."

The play is currently marked as a pass_touchdown == 1 and yards_gained positive etc.

I remember Ben Baldwin tweeting that when this happens, we should open an issue so that you can rescrape the data once NFL corrects this, so thought I'd point it out. Was surprised by how many points Anthony Miller had in fantasy football this week...

Thanks!

**Comment by guga31bb** [comment]
We automatically re-scrape on Wednesdays now so stuff like that gets fixed automatically, but thanks for the heads up- I've done a manual re-scrape on this game so it's fixed now in the package and will be fixed in the data repo when it updates tonight.
