### ISSUE TITLE
hi I found something odd with the PBPdata.

### ISSUE THREAD

**Issue by ak47twq** [guga31bb/nflfastR-data#34]
temp <- pbp %>%
     filter(special_teams_play == 1, season_type == "POST", rush == 1 | pass == 1) %>%
     view()
when i use this code , the outcome has 2 lines of S.Gostkowski field goal and extra point
i wonder if it is something i did or the PBPdata has a typo?
![1](https://user-images.githubusercontent.com/72854702/95957639-8526d380-0e32-11eb-9059-acee68324186.PNG)

**Comment by mrcaseb** [comment]
You are looking at postseason special teams plays. The two Gostkiowski plays didn't happen consecutively. They didn't even happen in the same game.

```r
library(dplyr)
nflfastR:::load_pbp(2016) %>%
  filter(special_teams_play == 1, season_type == "POST", rush == 1 | pass == 1) %>%
  select(game_id, play_id, desc)
```
![grafik](https://user-images.githubusercontent.com/38586519/95984693-e004fe80-0e23-11eb-952b-73cf67e2df95.png)

**Comment by mrcaseb** [comment]
Ben convinced me that I misunderstood the initial problem. 

```r
library(dplyr)
nflfastR:::load_pbp(1999:2020) %>%
  filter(special == 1, season_type == "POST", rush == 1 | pass == 1) %>%
  select(game_id, play_id, desc) %>% 
  view()
```

These two plays are the only special teams plays where `pass == 1`
![grafik](https://user-images.githubusercontent.com/38586519/95989017-fe6df880-0e29-11eb-8af5-2f2b3bfe3a11.png)

**Comment by ak47twq** [comment]
thx for reply😍

**Comment by guga31bb** [comment]
Closing this because we moved the issue to the main nflfastR repo
