### ISSUE TITLE
Feature request: cross-platform schedules

### ISSUE THREAD

**Issue by sansbacon** [guga31bb/nflfastR-data#37]
If there isn't a compelling reason for the current format, could you add it on the roadmap to add cross-platform formats for the schedule files as you do with the other data files? Thanks!

**Comment by sansbacon** [comment]
I used this to convert existing files. I assume there would be modest changes in the script that generate future files.

```
library(arrow)

for (i in 1999:2020) {
  basedir <- '~/nflfastR-data/schedules/'
  fn <- paste0(basedir, 'sched_', i, '.rds')
  dfr <- readRDS(fn)
  pfn <- paste0(basedir, 'sched_', i, '.parquet')
  cfn <- paste0(basedir, 'sched_', i, '.csv')
  write_parquet(dfr, pfn)
  write.csv2(dfr, cfn, row.names = FALSE)
}

```

**Comment by guga31bb** [comment]
We haven't bothered because this exists (which is the source for a lot of our games info anyway): https://github.com/leesharpe/nfldata/blob/master/data/games.csv
