### ISSUE TITLE
2020 rosters

### ISSUE THREAD

**Issue by paulz1** [guga31bb/nflfastR-data#38]
At very first thank you very much for your project.

While play-by-play data has a great value, I (and a lot of peoples as it seems) am very interested about roster data.
Actually roster-data finished at 2019.

I'd like to know if it's possible to put actual 2020 rosters ?

**Comment by mrcaseb** [comment]
Roster have been moved to another repo https://github.com/mrcaseb/nflfastR-roster

If you are using the R package nflfastR it's the function `fast_scraper_roster()` https://www.nflfastr.com/reference/fast_scraper_roster.html

If you are looking for csv data please see the above mentioned repo.
