### ISSUE TITLE
Jarvis Landry mis-credited for a TD in week 1 2019

### ISSUE THREAD

**Issue by jseibert575** [guga31bb/nflfastR-data#4]
Jarvis Landry is credited with a touchdown in week 1 of the 2019 season, against the Titans. Comparing against the game, it seems like he didn't actually score a touchdown here. I've fixed manually, but it should probably be fixed in the raw data. Thanks!

**Comment by guga31bb** [comment]
Do you have a code example? I'm guessing you're looking at `(3:11) (Shotgun) 6-B.Mayfield pass short left intended for 80-J.Landry INTERCEPTED by 21-M.Butler at CLE 38. 21-M.Butler for 38 yards, TOUCHDOWN.`

This was indeed a touchdown on a play he was targeted on (but for the other team). At least [here](https://rbsdm.com/stats/box_scores/?_inputs_&type=%22reg%22&away=%22TEN%22&home=%22CLE%22&year=%222019%22) he's being properly penalized by EPA so I *think* this is behaving as intended.

To count a receiver's touchdowns you'd probably want to filter to plays where interception == 0.

**Comment by jseibert575** [comment]
That's exactly right, thanks so much. Sorry about that! Appreciate the help.
