### ISSUE TITLE
Trouble installing 

### ISSUE THREAD

**Issue by TurnerBadowski** [guga31bb/nflfastR-data#41]
Sorry, I am new to R and I don't know if this is an nflfastr issue or something else. 

When I try to run this code

#needed to install `nflfastR`
install.packages("devtools")
devtools::install_github("mrcaseb/nflfastR")

I end up with 

package ‘backports’ successfully unpacked and MD5 sums checked
Error: Failed to install 'nflfastR' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘backports’

I've found 'backports' in my files, should I just delete the file and rerun the installation? 

Thanks in advance!

**Comment by guga31bb** [comment]
Yes I would try removing and re-installing "backports"

**Comment by TurnerBadowski** [comment]
I tried deleting that and then it just got really weird. I ended up reinstalling R and just successfully downloaded nflfastR.

Thanks for the help!
