### ISSUE TITLE
Negative yard line in variable end_yard_line (e.g. PHI -10)

### ISSUE THREAD

**Issue by cwnoyes** [guga31bb/nflfastR-data#44]
I have been using the data in file `play_by_play_2019.tar.gz` for analysis, and I am parsing the variable `end_yard_line` to get the field position for the next play. I noticed two lines in this file that seem to be off to me in that there is a negative number as the yard line. Here is an illustration of one of the examples:

|   play_id | game_id         |   old_game_id | side_of_field   |   yardline_100 | yrdln   | desc                                                                                                                                                                                                | end_yard_line   |
|----------:|:----------------|--------------:|:----------------|---------------:|:--------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------|
|      3219 | 2019_02_PHI_ATL |    2019091513 | PHI             |              8 | PHI 8   | (:21) (Shotgun) 2-M.Ryan pass short right intended for 81-A.Hooper INTERCEPTED by 47-N.Gerry at PHI 0. Touchback. PENALTY on PHI-96-D.Barnett, Unnecessary Roughness, 10 yards, enforced at PHI 20. | **PHI -10**         |
|      3257 | 2019_02_PHI_ATL |    2019091513 | PHI             |             90 | *PHI 10*  | (:12) (Shotgun) 72-H.Vaitai reported in as eligible.  11-C.Wentz pass short right to 86-Z.Ertz to PHI 16 for 6 yards (22-K.Neal).                                                                   | PHI 16          |

The cell I think is incorrect is in bold, and the value I think is correct is in italics.

**Comment by mrcaseb** [comment]
Thanks @cwnoyes!
This is a bug in the underlying data which I don't expect will be fixed by the NFL so I'll close this. If someone has an idea how to fix that manually in nflfastR, please feel free to open again.
