### ISSUE TITLE
2020_10_DEN_LV | 979 - Is that a "run" or a "no play"?

### ISSUE THREAD

**Issue by rmrui** [guga31bb/nflfastR-data#45]
(15:00) 28-J.Jacobs right guard to DEN 29 for 1 yard (55-B.Chubb). PENALTY on LV-75-B.Parker, Offensive Holding, 10 yards, enforced at DEN 30 - No Play.

Play type says "run" but I ask you guys if this should be a "no play" or not in "play_type".

**Comment by mrcaseb** [comment]
This is definitely weird and we should have a look. It's the only play in 2020 with `penalty == 1` and `"no_play"` in `desc` that is not listed as `"no_play"`

``` r
library(magrittr)

nflfastR:::load_pbp(2020) %>%
  dplyr::filter(stringr::str_detect(desc, "No Play"), play_type != "no_play") %>%
  dplyr::select(game_id, play_id, desc, play_type, penalty)
#> # A tibble: 3 x 5
#>   game_id     play_id desc                                     play_type penalty
#>   <chr>         <dbl> <chr>                                    <chr>       <dbl>
#> 1 2020_09_DE…    1713 (2:00) (Shotgun) 2-M.Ryan pass incomple… pass            0
#> 2 2020_10_DE…     979 (15:00) 28-J.Jacobs right guard to DEN … run             1
#> 3 2020_11_CI…    1114 (12:09) (Shotgun) 9-J.Burrow scrambles … run             0
```

<sup>Created on 2021-02-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mrcaseb** [comment]
Ok I have investigated it: this is a rare bug, where the `penalty_fix` variable is coming at us again @guga31bb. I have created an issue and a PR in nflfastR and will close this here. 

Thanks @rmrui !

**Comment by rmrui** [comment]
Anytime!
