### ISSUE TITLE
JAX Penalty Errors

### ISSUE THREAD

**Issue by williambjames** [guga31bb/nflfastR-data#47]
I've found an issue in which 2011-2015 data (from what I can tell based on penalty counts) miscredits some plays away from JAX, when JAX plays at home.
EX: game_id 2013_01_KC_JAX, play_id 1053
desc: 
(:52) (Punt formation) PENALTY on JAX-90-A.Branch, False Start, 5 yards, enforced at JAX 23 - No Play.

however the penalty_team == KC, not JAX

**Comment by mrcaseb** [comment]
This is now monitored in nflfastR and will be fixed soon. 

Thanks @williambjames
