### ISSUE TITLE
"drive" field includes the next drive's first play in the previous drive

### ISSUE THREAD

**Issue by cromwell421** [guga31bb/nflfastR-data#48]
The drive field is incorrect in some games where the first play of drive n is listed as drive n-1. 

For example, in 2020_16_ATL_KC game, the first play for KC (play_id 170) where Leveon ran the ball, it is listed as drive 1 even though ATL has already punted the play before. 

<img width="702" alt="Screen Shot 2020-12-30 at 1 59 18 PM" src="https://user-images.githubusercontent.com/32655686/103375293-dfd1e200-4aa7-11eb-8695-fde3c661ecc6.png">

Another example where SF's first play of drive 5 shows as drive 4

<img width="690" alt="Screen Shot 2020-12-30 at 2 07 05 PM" src="https://user-images.githubusercontent.com/32655686/103375477-57a00c80-4aa8-11eb-8fe1-9eb15850a14d.png">

I've noticed this in a few games for 2020 data (not checked previous seasons). It does not happen for each drive, but many of them.

**Comment by guga31bb** [comment]
Please use the `fixed_drive` field instead- `drive` is provided by NFL and has a million issues (as you've discovered)
