### ISSUE TITLE
Recent QB's missing from legacy_id_map

### ISSUE THREAD

**Issue by donald-keighley** [guga31bb/nflfastR-data#49]
It looks like there's a chunk of recent QB's missing from the legacy_id_map:

C.Newton | 32013030-2d30-3032-3739-33399bbb0097
J.Locker | 32013030-2d30-3032-3739-343665b0a7b1
B.Gabbert | 32013030-2d30-3032-3739-34386d7e96d3
C.Ponder | 32013030-2d30-3032-3739-35306cea4d9c
A.Dalton | 32013030-2d30-3032-3739-37334d29528c
C.Kaepernick | 32013030-2d30-3032-3739-373477e16970
T.Yates | 32013030-2d30-3032-3830-3930c7641ce7
T.Taylor | 32013030-2d30-3032-3831-3138b775ef66
G.McElroy | 32013030-2d30-3032-3831-343639e7f44e
T.Pryor | 32013030-2d30-3032-3838-3235f9b1e8b0
A.Davis | 32013030-2d30-3032-3839-35372ad9e22c
C.Keenum | 32013030-2d30-3032-3839-383680011105
M.Simms | 32013030-2d30-3032-3931-353182097190
T.Cadet | 32013030-2d30-3032-3932-3035b61cde07
K.Moore | 32013030-2d30-3032-3932-33342fd4327e
R.Wilson | 32013030-2d30-3032-3932-363323eefb5c
R.Lindley | 32013030-2d30-3032-3935-3331543baa9a
N.Foles | 32013030-2d30-3032-3935-3637b84f8e70
K.Cousins | 32013030-2d30-3032-3936-303492e9d55e
A.Luck | 32013030-2d30-3032-3936-363868835ca0
B.Weeden | 32013030-2d30-3032-3936-3737d1b9b493
B.Osweiler | 32013030-2d30-3032-3936-3832387475b8
R.Tannehill | 32013030-2d30-3032-3937-3031bbb58137
T.Bray | 32013030-2d30-3033-3031-35314afd422b
K.Allen | 32013030-2d30-3033-3032-3739a5751069
M.McGloin | 32013030-2d30-3033-3034-31396ad2dd9c
L.Bell | 32013030-2d30-3033-3034-3936441ea1c4
M.Glennon | 32013030-2d30-3033-3035-3230b20b479c
L.Jones | 32013030-2d30-3033-3035-32348f8bd074
E.Manuel | 32013030-2d30-3033-3035-3236366507d8
M.Barkley | 32013030-2d30-3033-3035-3333e8333411
G.Smith | 32013030-2d30-3033-3035-3635405348e4
C.Shaw | 32013030-2d30-3033-3036-3631c865686c
T.Savage | 32013030-2d30-3033-3130-3634af6ea87a
T.Bridgewater | 32013030-2d30-3033-3132-3337a759b614
D.Carr | 32013030-2d30-3033-3132-3830ee8bf3c4
A.McCarron | 32013030-2d30-3033-3132-38386b3121bc
J.Garoppolo | 32013030-2d30-3033-3133-34353afe165e
J.Landry | 32013030-2d30-3033-3133-3832ba34ef7f
B.Bortles | 32013030-2d30-3033-3134-30371c5cfd02
J.Manziel | 32013030-2d30-3033-3134-3039e3298e0a
J.Winston | 32013030-2d30-3033-3135-30339e998e6f
B.Petty | 32013030-2d30-3033-3135-36389915a7d0
B.Hundley | 32013030-2d30-3033-3135-3839c2d37962
T.Siemian | 32013030-2d30-3033-3231-3536ca98034d
S.Mannion | 32013030-2d30-3033-3232-3435dbcb2822
M.Mariota | 32013030-2d30-3033-3232-363844a90db1
B.Allen | 32013030-2d30-3033-3234-33349fe923c0
J.Driskel | 32013030-2d30-3033-3234-33369707963e
N.Sudfeld | 32013030-2d30-3033-3237-3932899dadbc
C.Wentz | 32013030-2d30-3033-3239-3530c5ee180a
D.Prescott | 32013030-2d30-3033-3330-37372d13d088
C.Kessler | 32013030-2d30-3033-3331-303462696929
J.Goff | 32013030-2d30-3033-3331-30361d564889
P.Lynch | 32013030-2d30-3033-3331-3038e948da3a
J.Brissett | 32013030-2d30-3033-3331-3139ba7e51e2
N.Mullens | 32013030-2d30-3033-3333-3139f5b32c5b
T.Hill | 32013030-2d30-3033-3333-3537640eb4b6
D.Watson | 32013030-2d30-3033-3335-33372bbab8b8
T.Cohen | 32013030-2d30-3033-3335-3536651f9951
M.Trubisky | 32013030-2d30-3033-3338-363967f6a360
P.Mahomes | 32013030-2d30-3033-3338-3733fa30c4fa
D.Kizer | 32013030-2d30-3033-3338-3939df045cc1
C.Beathard | 32013030-2d30-3033-3339-333693af7fb7
J.Rosen | 32013030-2d30-3033-3433-3433d2e30b97
K.Allen | 32013030-2d30-3033-3435-37371bc48d7c
L.Jackson | 32013030-2d30-3033-3437-39369c80073a
B.Mayfield | 32013030-2d30-3033-3438-3535737060f8
J.Allen | 32013030-2d30-3033-3438-3537f3a13a66
S.Darnold | 32013030-2d30-3033-3438-36394b743d00
K.Murray | 32013030-2d30-3033-3532-323871689b29
D.Haskins | 32013030-2d30-3033-3532-33323372c856
W.Grier | 32013030-2d30-3033-3532-35315617b0a0
G.Minshew II | 32013030-2d30-3033-3532-3839c25a936a
R.Finley | 32013030-2d30-3033-3536-3532a6148b47
D.Lock | 32013030-2d30-3033-3537-3034604f1124
D.Jones | 32013030-2d30-3033-3537-31306de02154
J.Robinson | 32013030-2d30-3033-3538-3331fa153077
T.Tagovailoa | 32013030-2d30-3033-3632-31321ff0777c
J.Herbert | 32013030-2d30-3033-3633-3535d3b834af
B.DiNucci | 32013030-2d30-3033-3633-38343a2e65ef
J.Hurts | 32013030-2d30-3033-3633-38395223e651
J.Burrow | 32013030-2d30-3033-3634-3432d92fc82e

**Comment by mrcaseb** [comment]
The legacy ID map is a helper to unify IDs of players that appear in the pbp data pre and in or post 2011. These players exist with two IDs in the data. The players you have mentioned shouldn't meet that criteria. 

However, the legacy ID map won't be used in a future version of nflfastR as we have a function to decode the IDs. 

Therefore I am going to close this.

**Comment by donald-keighley** [comment]
I see.  I was trying to join the roster data to the play by play data using the legacy map (since the roster data only has gsis_id) but apparently that's not what it's for.  Seems like it should be possible though?  Is that the plan for the new function?  For instance, Cam has a gsisId and a new_id.

Roster data:
   teamPlayers.displayName teamPlayers.gsisId
1:              Cam Newton         00-0027939

Play by play:
        passer                            passer_id
   1: C.Newton 32013030-2d30-3032-3739-33399bbb0097

**Comment by guga31bb** [comment]
https://www.nflfastr.com/articles/nflfastR.html#example-10-working-with-roster-and-position-data-1

**Comment by donald-keighley** [comment]
Thanks!
