### ISSUE TITLE
data discrepancies?

### ISSUE THREAD

**Issue by nickwan** [guga31bb/nflfastR-data#5]
hi hi, looking at this game: 
https://www.pro-football-reference.com/boxscores/200009030nor.htm

`game_id` in the CSV is `2000090304` in file `play_by_play_2000.csv.gz`  

i'm looking at `total_home_score` and `total_away_score` and the end of game score is 9-12, NOR-DET. however, sports ref has the game at 10-14, NOR-DET. ESPN has a box score that's also similar (http://www.espn.com/nfl/2000/20000903/recap/detnor.html) so i'm guessing the 10-14 score is the "real" score. unsure how persistent this is across the data, but this was one error i found.

**Comment by guga31bb** [comment]
Hi Nick, thanks for using the data! This is a bug in the underlying data provided by the NFL (RIP) where the NFL did not record point-after-touchdowns following defensive touchdowns (including punt returns). You found a game with two of those!

``` r
pbp %>%
  filter(home_team == 'NO' & away_team == 'DET') %>%
    filter(play_id %in% c(330,365, 2686, 2767)) %>%
  select(desc, posteam, total_home_score, total_away_score)

# A tibble: 4 x 4
  desc                                                                                           posteam total_home_score total_away_score
  <chr>                                                                                          <chr>              <dbl>            <dbl>
1 "(9:46) S.Case pass intended for D.Sloan INTERCEPTED by S.Knight at DET 37. S.Knight for 37 y~ DET                    6                0
2 "T.Gowin kicks 65 yards from NO 30 to DET 5. D.Howard to DET 20 for 15 yards (T.Franz)."       DET                    6                0
3 "(2:28) T.Gowin punts 58 yards to DET 5, Center-K.Houser. D.Howard for 95 yards, TOUCHDOWN.\n~ NO                     6               12
4 "J.Hanson kicks 66 yards from DET 30 to NO 4. C.Morton pushed ob at NO 49 for 45 yards (J.Han~ NO                     6               12
```
So following the scores, the next plays are kickoffs, not the points after (the second one was a 2 point conversion).

This also affected nflscrapR as well, BUT I just checked the new API and the NFL has fixed this issue there. So stay tuned...
