### ISSUE TITLE
Play classified as "no-play" because of a flag that didn't wipe out a play

### ISSUE THREAD

**Issue by jseibert575** [guga31bb/nflfastR-data#7]
In week 6, 2019 (Giants @ Patriots), Brady threw a pick and then Markus Golden was flagged on the return for unnecessary roughness. The play_type is listed as "no_play", even though the flag got enforced after the interception return. play_id is 455 in week 6 2019, for reference. If this is on purpose and I'm just misunderstanding the classification, my apologies!

**Comment by jseibert575** [comment]
Similar shows up in week 13, with Patriots against the Texans. Brady threw a pick to Bradley Roby, who got flagged for unsportsmanlike conduct after the pick, and the play is listed as "no_play."

**Comment by jseibert575** [comment]
Just saw that "no_play" is given for anything where a penalty is called. I'll close this now, sorry to bother!

**Comment by guga31bb** [comment]
This still might be a bug but don't have time to check right now. What does `play_type_nfl` say on these plays?

**Comment by jseibert575** [comment]
Both listed as `PASS` in `play_type_nfl`. Thanks!

**Comment by guga31bb** [comment]
Got it, thanks. `play_type_nfl` is what the NFL provides itself, while `play_type` is something inferred in the code. I'm guessing this is probably a bug but since the NFL has removed access to this data we probably won't bother fixing it.

**Comment by jseibert575** [comment]
Okay, that's what I was thinking, but just wanted to check and see if I was on the right path. Easy enough to get around it by querying differently. Too bad about NFL APIs :/ 

Thanks for your help!

**Comment by guga31bb** [comment]
Closing this because it's been fixed in the development branch
